on:
  workflow_call:

env:
  terraform_version: 1.14.3
  TF_VAR_gitlab_pat: ${{ secrets.GITLAB_TOKEN }}
  GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "${terraform_version}"
      - run: terraform init
      - run: terraform test